version: '2.1'

services:
    users-db:
        container_name: users-db
        build: https://github.com/zhlooking/flask-microservices-users.git#master:plato/db
        ports:
            - 5435:5432     # expose ports - HOST:CONTAINER
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        healthcheck:
            test: exit 0

    users-service:
        container_name: users-service
        build: https://github.com/zhlooking/flask-microservices-users.git
        expose:
            - '5000'
        environment:
            - APP_SETTINGS=plato.config.ProductionConfig
            - DATABASE_URL=postgres://postgres:postgres@users-db:5432/users_prod
            - DATABASE_TEST_URL=postgres://postgres:postgres@users-db:5432/users_test
            - SECRET_KEY=${SECRET_KEY}
        depends_on:
            users-db:
                condition: service_healthy
        links:
            - users-db
        command: gunicorn -b 0.0.0.0:5000 manage:app

    nginx:
        contaier-name: nginx
        build: ./nginx/
        restart: always
        ports:
            - 80:80
        depends_on:
            users-service:
                condition: service_started
            web-service:
                condition: service_started
        links:
            - users-service
            - web-service

    web-service:
        container_name: web-service
        build:
            context: https://github.com/zhlooking/flask-microservices-client.git
            args:
                - NODE_ENV=development
                - REACT_APP_USERS_SERVICE_URL=${REACT_APP_USERS_SERVICE_URL}
        ports:
            - '9000:9000'
        depends_on:
            users-service:
                condition: service_started
        links:
            - users-service
