"""empty message

Revision ID: 500d7818ef8f
Revises: 77c36283c54d
Create Date: 2017-06-22 14:26:37.498312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '500d7818ef8f'
down_revision = '77c36283c54d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
